"""add stats.creationtime col

Revision ID: 8b9ab4367d72
Revises: 336474f0fb95
Create Date: 2023-04-19 18:12:16.686323

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime, timezone, timedelta


# revision identifiers, used by Alembic.
revision = '8b9ab4367d72'
down_revision = '336474f0fb95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('creationtime', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone(timedelta(0))))))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'creationtime')
    # ### end Alembic commands ###
